# Continuous integration

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        enable-cuda: ["no"] # ["yes", "no"] probably not possible to use github CI with CUDA requirements

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pybind11 numpy jaxlib

    - name: Checks with pre-commit
      uses: pre-commit/action@v3.0.0

    - name: Test with pytest
      env:
        BUILD_WITH_CUDA: ${{ matrix.enable-cuda}}
      run: |
        echo "BUILD_WITH_CUDA=$BUILD_WITH_CUDA"
        python setup.py build_ext --inplace
        python -m pip install .
        python -m pytest --durations=0